the1_dhondt:
	gcc the1_dhondt.c -o the1_dhondt -pedantic-errors -ansi -Wall
the1_pyramid:
	gcc the1_pyramid.c -o the1_pyramid -pedantic-errors -ansi -Wall
clear:
	rm the1_dhondt the1_pyramid
all: clear the1_dhondt the1_pyramid